#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: 5424026
#
Name     : R-Rserve
Version  : 1.8.15
Release  : 52
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/Rserve_1.8-15.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/Rserve_1.8-15.tar.gz
Summary  : Versatile R Server
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: R-Rserve-lib = %{version}-%{release}
Requires: R-Rserve-license = %{version}-%{release}
BuildRequires : buildreq-R
BuildRequires : openssl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
which allows binary requests to be sent to R. Every
	     connection has a separate workspace and working
	     directory. Client-side implementations are available
	     for popular languages such as C/C++ and Java, allowing
	     any application to use facilities of R without the need of
	     linking to R code. Rserve supports remote connection,
	     user authentication and file transfer. A simple R client
	     is included in this package as well. In addition, it can
	     also act as a secure WebSockets and HTTP/HTTPS server.

%package lib
Summary: lib components for the R-Rserve package.
Group: Libraries
Requires: R-Rserve-license = %{version}-%{release}

%description lib
lib components for the R-Rserve package.


%package license
Summary: license components for the R-Rserve package.
Group: Default

%description license
license components for the R-Rserve package.


%prep
%setup -q -n Rserve
pushd ..
cp -a Rserve buildavx2
popd
pushd ..
cp -a Rserve buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735110610

%install
export SOURCE_DATE_EPOCH=1735110610
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-Rserve
cp %{_builddir}/Rserve/LICENSE %{buildroot}/usr/share/package-licenses/R-Rserve/e9e85ed32466ac3d8e24bec27f9f54c717328a7c || :
cp %{_builddir}/Rserve/src/client/cxx/COPYING %{buildroot}/usr/share/package-licenses/R-Rserve/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/Rserve/src/client/java/LICENSE %{buildroot}/usr/share/package-licenses/R-Rserve/1041fd8e7abbd214dded03c980ad5bd84f03910e || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/Rserve/libs/Rserve
/V3/usr/lib64/R/library/Rserve/libs/Rserve.dbg
/V3/usr/lib64/R/library/Rserve/libs/forward
/V4/usr/lib64/R/library/Rserve/libs/Rserve
/V4/usr/lib64/R/library/Rserve/libs/Rserve.dbg
/V4/usr/lib64/R/library/Rserve/libs/forward
/usr/lib64/R/library/Rserve/DESCRIPTION
/usr/lib64/R/library/Rserve/INDEX
/usr/lib64/R/library/Rserve/LICENSE
/usr/lib64/R/library/Rserve/Meta/Rd.rds
/usr/lib64/R/library/Rserve/Meta/features.rds
/usr/lib64/R/library/Rserve/Meta/hsearch.rds
/usr/lib64/R/library/Rserve/Meta/links.rds
/usr/lib64/R/library/Rserve/Meta/nsInfo.rds
/usr/lib64/R/library/Rserve/Meta/package.rds
/usr/lib64/R/library/Rserve/NAMESPACE
/usr/lib64/R/library/Rserve/NEWS
/usr/lib64/R/library/Rserve/R/Rserve
/usr/lib64/R/library/Rserve/R/Rserve.rdb
/usr/lib64/R/library/Rserve/R/Rserve.rdx
/usr/lib64/R/library/Rserve/help/AnIndex
/usr/lib64/R/library/Rserve/help/Rserve.rdb
/usr/lib64/R/library/Rserve/help/Rserve.rdx
/usr/lib64/R/library/Rserve/help/aliases.rds
/usr/lib64/R/library/Rserve/help/paths.rds
/usr/lib64/R/library/Rserve/html/00Index.html
/usr/lib64/R/library/Rserve/html/R.css
/usr/lib64/R/library/Rserve/java/REngine.jar
/usr/lib64/R/library/Rserve/java/Rserve.jar
/usr/lib64/R/library/Rserve/libs/Rserve
/usr/lib64/R/library/Rserve/libs/Rserve.dbg
/usr/lib64/R/library/Rserve/libs/forward

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/Rserve/libs/Rserve.so
/V4/usr/lib64/R/library/Rserve/libs/Rserve.so
/usr/lib64/R/library/Rserve/libs/Rserve.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-Rserve/1041fd8e7abbd214dded03c980ad5bd84f03910e
/usr/share/package-licenses/R-Rserve/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/R-Rserve/e9e85ed32466ac3d8e24bec27f9f54c717328a7c
